# Generated by Django 5.2.1 on 2025-05-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('editora', models.CharField(blank=True, max_length=100)),
                ('ano_publicacao', models.PositiveIntegerField()),
                ('isbn', models.CharField(blank=True, max_length=13)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='livros/')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas_livros/')),
            ],
        ),
    ]
