# Generated by Django 5.2.1 on 2025-06-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('Palestra', 'Palestra'), ('Workshop', 'Workshop'), ('Feira', 'Feira'), ('Outra', 'Outra')], max_length=20)),
                ('data', models.DateField()),
                ('local', models.CharField(blank=True, max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='atividades/')),
            ],
        ),
    ]
