# Generated by Django 5.2.1 on 2025-06-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_atividade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='ano_publicacao',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='arquivo_pdf',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='editora',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='isbn',
        ),
        migrations.AddField(
            model_name='livro',
            name='ano',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(),
        ),
    ]
