# Generated by Django 5.2.1 on 2025-06-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_livro_ano_publicacao_remove_livro_arquivo_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('lider', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
