# Generated by Django 5.2.1 on 2025-06-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_grupopesquisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupopesquisa',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grupopesquisa',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='grupos/'),
        ),
        migrations.AddField(
            model_name='grupopesquisa',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
