# Generated by Django 5.2.1 on 2025-06-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_destaque_remove_grupopesquisa_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='pet_destaques/')),
                ('link', models.URLField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('SI', 'Sistemas de Informação'), ('CC', 'Ciência da Computação')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoPET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='projetos_pet/')),
                ('pet_tipo', models.CharField(choices=[('SI', 'PET Sistemas de Informação'), ('CC', 'PET Ciência da Computação')], max_length=2)),
            ],
        ),
    ]
