# Generated by Django 5.2.1 on 2025-06-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_petdestaque_projetopet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetDestaque',
        ),
        migrations.AddField(
            model_name='grupopesquisa',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grupopesquisa',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projetopet',
            name='grupo',
            field=models.CharField(choices=[('SI', 'Sistemas de Informação'), ('CC', 'Ciência da Computação')], default='exit', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetopet',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projetopet',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projetos_pet/'),
        ),
        migrations.AlterField(
            model_name='projetopet',
            name='pet_tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projetopet',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
