# Generated by Django 5.2.1 on 2025-06-20 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_delete_petdestaque_grupopesquisa_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='conteudo',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='data_publicacao',
        ),
        migrations.AddField(
            model_name='noticia',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(default='default.jpg', upload_to='noticias/'),
        ),
    ]
