# Generated by Django 5.2.1 on 2025-07-08 02:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_publicacao_rename_conteudo_noticia_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao_curta', models.CharField(help_text='Aparece no card do carrossel na página inicial.', max_length=255)),
                ('imagem', models.ImageField(upload_to='eventos_imagens/')),
                ('conteudo_completo', models.TextField()),
                ('data_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
