# Generated by Django 5.2.1 on 2025-07-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
