# Generated by Django 5.2.1 on 2025-07-08 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_noticia_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.CharField(help_text='Um resumo curto da notícia para a página inicial.', max_length=255),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem de destaque da notícia (opcional).', null=True, upload_to='noticias/'),
        ),
    ]
