# Generated by Django 5.2.1 on 2025-07-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_alter_noticia_data_alter_noticia_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='resumo',
            field=models.TextField(blank=True, help_text='Uma breve descrição ou resumo do artigo.', null=True),
        ),
    ]
