# Generated by Django 5.2.1 on 2025-07-09 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_publicacao_resumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='data_publicacao',
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem de destaque do projeto (opcional).', null=True, upload_to='projetos_alunos/'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='link',
            field=models.URLField(blank=True, help_text='Link para o repositório ou site do projeto (opcional).', null=True),
        ),
    ]
